### ISSUE TITLE
Toggle Light And Dark Mode

### ISSUE THREAD

**Issue by hamidabdulmalik** [onesine/react-tailwindcss-datepicker#17]
First of all, wonderful product. So I was just wondering how to toggle the mode from dark to light. Thank you.

**Comment by ethan1341** [comment]
I'm having the same problem. 

  <Datepicker
            value={value}
            onChange={handleValueChange}
            showShortcuts={true}
            primaryColor={"violet"}
        />

no matter what I change the primary color too its always dark. I wonder if the css is getting over written

**Comment by JefteCaro** [comment]
@hamidabdulmalik 

Thank you for the feedback!

You can override the dark mode of the input with [`inputClassName`](https://react-tailwindcss-datepicker.vercel.app/props#input-class) prop

```js
<Datepicker 
  inputClassName="font-normal bg-green-100 dark:bg-green-900 dark:placeholder:text-green-100" 
  value={value} 
  onChange={handleValueChange} 
/>
```

**Comment by onesine** [comment]
Hi @hamidabdulmalik 👋

Thanks for your feadback.

By following the institutions in the tailwind doc https://tailwindcss.com/docs/dark-mode. You should be able to switch the datepicker to dark mode. This is exactly what we did in our document https://react-tailwindcss-datepicker.vercel.app/theming-options#dark-mode.

Otherwise @NoahMLoomis  has already said the main thing, and I'm just repeating it. You can also use the alternative that @JefteCaro  suggests, the best way being to follow the tailwind doc.

I think we should be able to close this issue now.
