### ISSUE TITLE
Format issue

### ISSUE THREAD

**Issue by aleguern** [onesine/react-tailwindcss-datepicker#25]
Hi, I love the lib but I'm surprised by the date format.
In the documentation, it is written that it should be YYYY-MM-DD, but today is the 4th and I'm getting 2023-1-4. 
I was expecting to have leading zeros (2023-01-04) as the norm ISO expect ? [ISO 8601](https://www.iso.org/iso-8601-date-and-time-format.html) or [ISO 8601 norm](https://www.w3.org/TR/NOTE-datetime)
(I can open a PR if necessary to look at the necessary changes)

**Comment by NoahMLoomis** [comment]
The default is indeed YYYY-MM-DD, so it should've been 2023-01-04. Testing it today, I'm getting 2023-01-03. Must be a bug. Are you overriding the `displayFormat` prop accidentally? A potential workaround could also be to specify the `displayFormat="YYYY-MM-DD`, that could fix the bug

**Comment by aleguern** [comment]
I'm using the following options :

```
i18n={"fr"}
inputClassName=""
value={{
  startDate: date,
  endDate: date,
}}
useRange={false}
asSingle={true}
startFrom={new Date(Date.now())}
onChange={(newValue) => console.log(newValue)}
```

The fix I made was to convert the date with the Date object: (it fixes the leading zero missing) 
```
console.log(date); // 2020-1-1
const leadingZeroDate = new Date(date);
console.log(leadingZeroDate) // 2020-01-01
```

**Comment by NoahMLoomis** [comment]
Weird bug. Could be related to the i18n format?

**Comment by JefteCaro** [comment]
Hi @aleguern,

Thank you for the feedback. We'll try to look into it.
or, opening PRs are very much welcome.

**Comment by devinmatte** [comment]
Hi I'm running into this same issue in the latest 1.4.2 release from npm. Is the fix for this not in that release?
When selecting a date from the picker I'm getting `2023-2-7` even when setting `displayFormat={'YYYY-MM-DD'}`

Any thoughts? I can try manually fixing the output before passing it to downstream functions, but that still seems like an incorrect result

**Comment by hcusto** [comment]
I have the same problem also with latest version.

**Comment by AnalogMemory** [comment]
@JefteCaro there is open PR that would fix this issue

https://github.com/onesine/react-tailwindcss-datepicker/pull/61

**Comment by onesine** [comment]
Hello everyone 👋

Sorry for the delay. Thanks for your interest in this package. It seems to be a strange bug indeed. I have never encountered this problem since. Maybe it's because I haven't been around lately to follow the evolution of the package.

Thanks for your PR @AnalogMemory. I will take a look at it.
