### ISSUE TITLE
[Feature Request] Custom theme classes applying to calendar 

### ISSUE THREAD

**Issue by liamjbarry** [onesine/react-tailwindcss-datepicker#8]
Hi,

Great project, really nice and easy to use and has all the features I need and more! I am currently working on a project that requires specific colours for theming/branding etc. 

I have used tailwind.config.js to define a custom colour palette as described in the tailwind docs and I would like to use that class in the calendar to give the correct colours, is this something that could be supported by this package? I plan to (at some point) have a go at writing this myself and submitting a PR if I manage to get it working. In the meantime any suggestions on how to achieve this would be welcomed.

TIA

**Comment by onesine** [comment]
Hi 👋  @liamjbarry 

Thank you very much for your feature request. I am very happy that you find it easy to use and that you find it so enjoyable.

Your request is very relevant as it was planned since the beginning of the project. Only I had some constraints and finally proposed some basic themes.

Very soon this feature will be supported in the next versions. 

There are requests on the packages I released for the moment. So I'm a bit overwhelmed at the moment. I will be glad to see your PR and contribute with you on this package.

**Comment by nLamprok** [comment]
@onesine hey! 👋

Indeed, incredible work so far. This was indeed missing from the community. I believe to handle all people's needs, you should probably allow overloading classes for different parts of the UI (such as the input, the container, the popup etc.). 

Because of class priority (aka the order in which you type them), if someone wants to add custom classes to set specific styles (even colours, backgrounds etc) he/she should be able to just pass the overloaded classes. For example:

```js
<DatePicker
  overloadInputClasses='bg-[#5551ff] py-2'
/>
```

I believe it's relatively easy to implement that. I can probably try to contribute to this with a PR if I find some time.

Again, thanks a lot for this :)

**Comment by onesine** [comment]
Hi @nLamprok   👋

Thank you for your feedbacks. I don't have enough time right now to respond to everyone's needs. I will do my best, but it would be interesting to have other people participate with me in improving this package. There are enough features that could be added and as I receive many feature requests.

Thank you also for the example you have proposed. I will be very happy to see your PR very soon 😃.

**Comment by JefteCaro** [comment]
New props available as of [v1.2.0](https://github.com/onesine/react-tailwindcss-datepicker/releases/tag/v1.2.0):

* to overload input classNames : `inputClassName`
* to add classNames to input container: `containerClassName` 
* to disable the input: `disabled`

```js
<Datepicker
  disabled
  inputClassName="text-base font-normal"
  containerClassName="mt-2"
/>
```

**Comment by onesine** [comment]
I will update the documentation very soon. Thanks @JefteCaro

**Comment by rxflame** [comment]
I've tried to customize the background color but it doesn't seem to work it out, this would be amazing if it was possible ! Congratz awesome project by the way
